---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: bot
  labels:
    app: bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
        service.opentelemetry.io/name: go-faster.bot
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8090'
    spec:
      volumes:
        - name: atlas
          secret:
            secretName: atlas
      initContainers:
        - name: migrate
          image: ghcr.io/go-faster/bot/migrate:main
          volumeMounts:
            - mountPath: "/root/.config/"
              name: atlas
              readOnly: true
          args:
            - --config
            - file://root/.config/atlas.hcl
            - --env
            - prod
            - migrate
            - apply
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 500m
              memory: 128M
      containers:
        - name: bot
          image: ghcr.io/go-faster/bot:main
          args:
            - server
          startupProbe:
            httpGet:
              path: /probe/startup
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          ports:
            - containerPort: 8090
              protocol: TCP
              name: metrics
            - containerPort: 8080
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 256M
            limits:
              cpu: "3"
              memory: 512M
          env:
            - name: GOMEMLIMIT
              value: "512MiB"
            - name: GOMAXPROCS
              value: "2"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "8090"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.bot"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo-distributor.monitoring.svc.cluster.local:4317"
            - name: HOME
              value: /cache
            - name: HTTP_ADDR
              value: 0.0.0.0:8080
            - name: TG_NOTIFY_GROUP
              value: go_faster_news
            - name: TG_DEPLOY_NOTIFY_GROUP
              value: go_faster_news
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: BOT_TOKEN
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_ID
            - name: APP_HASH
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: APP_HASH
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_PRIVATE_KEY
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_SECRET
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_APP_ID
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_INSTALLATION_ID
              value: "26766968"
            - name: OPENAI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: OPENAI_TOKEN
            - name: CLICKHOUSE_ADDR
              value: chendpoint-db.clickhouse.svc.cluster.local:9000
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: CLICKHOUSE_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: DATABASE_URL
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: faster
  name: job-commits
  labels:
    app: bot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: ghcr.io/go-faster/bot:main
            imagePullPolicy: IfNotPresent
            args:
              - job
              - commits
          restartPolicy: OnFailure