---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-clickhouse
  namespace: faster-monitoring
data:
  config.yaml: |
    address: tcp://db.mcs.local:9000
    spans_table:
    spans_index_table:
    operations_table:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jaeger
    k8s-app: jaeger
  name: jaeger
  namespace: faster-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      annotations:
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: jaeger
        k8s-app: jaeger
        prometheus: "true"
    spec:
      containers:
      - args:
        - --grpc-storage-plugin.binary=/plugin/jaeger-clickhouse
        - --grpc-storage-plugin.configuration-file=/plugin-config/config.yaml
        - --grpc-storage-plugin.log-level=info
        env:
        - name: SPAN_STORAGE_TYPE
          value: grpc-plugin
        volumeMounts:
          - mountPath: /plugin-config
            name: plugin-config
            readOnly: true
          - mountPath: /plugin
            name: plugin-volume
          - mountPath: /tmp
            name: tmp
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 1
        image: jaegertracing/all-in-one:1.36
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 5778
          name: api
          protocol: TCP
        - containerPort: 6831
          name: jaeger-thrift
          protocol: UDP
        - containerPort: 14250
          name: span-grpc
          protocol: TCP
        - containerPort: 14268
          name: span-http
          protocol: TCP
        - containerPort: 14269
          name: metrics
          protocol: TCP
        - containerPort: 16685
          name: grpc
          protocol: TCP
        - containerPort: 16686
          name: ui
          protocol: TCP
        resources:
          limits:
              cpu: 500m
              memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
      initContainers:
        - image: ghcr.io/jaegertracing/jaeger-clickhouse:0.11.0
          name: install-plugin
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /plugin-config
              name: plugin-config
            - mountPath: /plugin
              name: plugin-volume
            - mountPath: /tmp
              name: tmp
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: jaeger-clickhouse
        name: plugin-config
      - emptyDir: {}
        name: plugin-volume
      - emptyDir: {}
        name: tmp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jaeger
    k8s-app: jaeger
    prometheus: "true"
  name: jaeger
  namespace: faster-monitoring
spec:
  ports:
    - name: api
      port: 5778
      protocol: TCP
      targetPort: 5778
    - name: jaeger-thrift
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: span-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: span-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: grpc
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: ui
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
