apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jaeger
    k8s-app: jaeger
  name: jaeger
  namespace: faster-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      annotations:
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: jaeger
        k8s-app: jaeger
        prometheus: "true"
    spec:
      containers:
      - args:
        - --memory.max-traces
        - "10000"
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        image: jaegertracing/all-in-one:1.36
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 5778
          name: api
          protocol: TCP
        - containerPort: 6831
          name: jaeger-thrift
          protocol: UDP
        - containerPort: 14250
          name: span-grpc
          protocol: TCP
        - containerPort: 14268
          name: span-http
          protocol: TCP
        - containerPort: 14269
          name: metrics
          protocol: TCP
        - containerPort: 16685
          name: grpc
          protocol: TCP
        - containerPort: 16686
          name: ui
          protocol: TCP
        resources:
          limits:
              cpu: 500m
              memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jaeger
    k8s-app: jaeger
    prometheus: "true"
  name: jaeger
  namespace: faster-monitoring
spec:
  ports:
    - name: api
      port: 5778
      protocol: TCP
      targetPort: 5778
    - name: jaeger-thrift
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: span-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: span-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: grpc
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: ui
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
