---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bot
  namespace: faster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bot
  endpoints:
    - port: metrics
