---
apiVersion: v1
kind: Service
metadata:
  namespace: faster
  name: bot
  labels:
    app: bot
    prometheus: "true"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http_bot
    - port: 80
      protocol: TCP
      targetPort: 8081
      name: http_api
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app: bot
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot
  namespace: faster
  labels:
    app: bot
spec:
  ingressClassName: cilium
  rules:
  - host: bot.go-faster.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bot
            port:
              name: http_bot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: faster
  labels:
    app: bot
spec:
  ingressClassName: cilium
  rules:
    - host: api.go-faster.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot
                port:
                  name: http_api
