---
apiVersion: v1
kind: Service
metadata:
  namespace: faster
  name: bot
  labels:
    app.kubernetes.io/name: bot
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-bot
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: http-api
    - port: 8090
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app.kubernetes.io/name: bot
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot
  namespace: faster
  labels:
    app.kubernetes.io/name: bot
spec:
  ingressClassName: nginx
  rules:
  - host: bot.gotd.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bot
            port:
              name: http-bot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: faster
  labels:
    app.kubernetes.io/name: bot
spec:
  ingressClassName: nginx
  rules:
    - host: api.gotd.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot
                port:
                  name: http-api
