// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/lastchannelmessage"
	"github.com/go-faster/bot/internal/ent/predicate"
)

// LastChannelMessageUpdate is the builder for updating LastChannelMessage entities.
type LastChannelMessageUpdate struct {
	config
	hooks    []Hook
	mutation *LastChannelMessageMutation
}

// Where appends a list predicates to the LastChannelMessageUpdate builder.
func (_u *LastChannelMessageUpdate) Where(ps ...predicate.LastChannelMessage) *LastChannelMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *LastChannelMessageUpdate) SetMessageID(v int) *LastChannelMessageUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *LastChannelMessageUpdate) SetNillableMessageID(v *int) *LastChannelMessageUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *LastChannelMessageUpdate) AddMessageID(v int) *LastChannelMessageUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// Mutation returns the LastChannelMessageMutation object of the builder.
func (_u *LastChannelMessageUpdate) Mutation() *LastChannelMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LastChannelMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LastChannelMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LastChannelMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LastChannelMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LastChannelMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastchannelmessage.Table, lastchannelmessage.Columns, sqlgraph.NewFieldSpec(lastchannelmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastchannelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LastChannelMessageUpdateOne is the builder for updating a single LastChannelMessage entity.
type LastChannelMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LastChannelMessageMutation
}

// SetMessageID sets the "message_id" field.
func (_u *LastChannelMessageUpdateOne) SetMessageID(v int) *LastChannelMessageUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *LastChannelMessageUpdateOne) SetNillableMessageID(v *int) *LastChannelMessageUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *LastChannelMessageUpdateOne) AddMessageID(v int) *LastChannelMessageUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// Mutation returns the LastChannelMessageMutation object of the builder.
func (_u *LastChannelMessageUpdateOne) Mutation() *LastChannelMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the LastChannelMessageUpdate builder.
func (_u *LastChannelMessageUpdateOne) Where(ps ...predicate.LastChannelMessage) *LastChannelMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LastChannelMessageUpdateOne) Select(field string, fields ...string) *LastChannelMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LastChannelMessage entity.
func (_u *LastChannelMessageUpdateOne) Save(ctx context.Context) (*LastChannelMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LastChannelMessageUpdateOne) SaveX(ctx context.Context) *LastChannelMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LastChannelMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LastChannelMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LastChannelMessageUpdateOne) sqlSave(ctx context.Context) (_node *LastChannelMessage, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastchannelmessage.Table, lastchannelmessage.Columns, sqlgraph.NewFieldSpec(lastchannelmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LastChannelMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lastchannelmessage.FieldID)
		for _, f := range fields {
			if !lastchannelmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lastchannelmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	_node = &LastChannelMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastchannelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
