// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/lastchannelmessage"
	"github.com/go-faster/bot/internal/ent/predicate"
)

// LastChannelMessageUpdate is the builder for updating LastChannelMessage entities.
type LastChannelMessageUpdate struct {
	config
	hooks    []Hook
	mutation *LastChannelMessageMutation
}

// Where appends a list predicates to the LastChannelMessageUpdate builder.
func (lcmu *LastChannelMessageUpdate) Where(ps ...predicate.LastChannelMessage) *LastChannelMessageUpdate {
	lcmu.mutation.Where(ps...)
	return lcmu
}

// SetMessageID sets the "message_id" field.
func (lcmu *LastChannelMessageUpdate) SetMessageID(i int) *LastChannelMessageUpdate {
	lcmu.mutation.ResetMessageID()
	lcmu.mutation.SetMessageID(i)
	return lcmu
}

// AddMessageID adds i to the "message_id" field.
func (lcmu *LastChannelMessageUpdate) AddMessageID(i int) *LastChannelMessageUpdate {
	lcmu.mutation.AddMessageID(i)
	return lcmu
}

// Mutation returns the LastChannelMessageMutation object of the builder.
func (lcmu *LastChannelMessageUpdate) Mutation() *LastChannelMessageMutation {
	return lcmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lcmu *LastChannelMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lcmu.sqlSave, lcmu.mutation, lcmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lcmu *LastChannelMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := lcmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lcmu *LastChannelMessageUpdate) Exec(ctx context.Context) error {
	_, err := lcmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcmu *LastChannelMessageUpdate) ExecX(ctx context.Context) {
	if err := lcmu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lcmu *LastChannelMessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastchannelmessage.Table, lastchannelmessage.Columns, sqlgraph.NewFieldSpec(lastchannelmessage.FieldID, field.TypeInt64))
	if ps := lcmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcmu.mutation.MessageID(); ok {
		_spec.SetField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := lcmu.mutation.AddedMessageID(); ok {
		_spec.AddField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lcmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastchannelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lcmu.mutation.done = true
	return n, nil
}

// LastChannelMessageUpdateOne is the builder for updating a single LastChannelMessage entity.
type LastChannelMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LastChannelMessageMutation
}

// SetMessageID sets the "message_id" field.
func (lcmuo *LastChannelMessageUpdateOne) SetMessageID(i int) *LastChannelMessageUpdateOne {
	lcmuo.mutation.ResetMessageID()
	lcmuo.mutation.SetMessageID(i)
	return lcmuo
}

// AddMessageID adds i to the "message_id" field.
func (lcmuo *LastChannelMessageUpdateOne) AddMessageID(i int) *LastChannelMessageUpdateOne {
	lcmuo.mutation.AddMessageID(i)
	return lcmuo
}

// Mutation returns the LastChannelMessageMutation object of the builder.
func (lcmuo *LastChannelMessageUpdateOne) Mutation() *LastChannelMessageMutation {
	return lcmuo.mutation
}

// Where appends a list predicates to the LastChannelMessageUpdate builder.
func (lcmuo *LastChannelMessageUpdateOne) Where(ps ...predicate.LastChannelMessage) *LastChannelMessageUpdateOne {
	lcmuo.mutation.Where(ps...)
	return lcmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lcmuo *LastChannelMessageUpdateOne) Select(field string, fields ...string) *LastChannelMessageUpdateOne {
	lcmuo.fields = append([]string{field}, fields...)
	return lcmuo
}

// Save executes the query and returns the updated LastChannelMessage entity.
func (lcmuo *LastChannelMessageUpdateOne) Save(ctx context.Context) (*LastChannelMessage, error) {
	return withHooks(ctx, lcmuo.sqlSave, lcmuo.mutation, lcmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lcmuo *LastChannelMessageUpdateOne) SaveX(ctx context.Context) *LastChannelMessage {
	node, err := lcmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lcmuo *LastChannelMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := lcmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcmuo *LastChannelMessageUpdateOne) ExecX(ctx context.Context) {
	if err := lcmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lcmuo *LastChannelMessageUpdateOne) sqlSave(ctx context.Context) (_node *LastChannelMessage, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastchannelmessage.Table, lastchannelmessage.Columns, sqlgraph.NewFieldSpec(lastchannelmessage.FieldID, field.TypeInt64))
	id, ok := lcmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LastChannelMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lcmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lastchannelmessage.FieldID)
		for _, f := range fields {
			if !lastchannelmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lastchannelmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lcmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcmuo.mutation.MessageID(); ok {
		_spec.SetField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := lcmuo.mutation.AddedMessageID(); ok {
		_spec.AddField(lastchannelmessage.FieldMessageID, field.TypeInt, value)
	}
	_node = &LastChannelMessage{config: lcmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lcmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastchannelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lcmuo.mutation.done = true
	return _node, nil
}
