// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/prnotification"
)

// PRNotificationCreate is the builder for creating a PRNotification entity.
type PRNotificationCreate struct {
	config
	mutation *PRNotificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRepoID sets the "repo_id" field.
func (pnc *PRNotificationCreate) SetRepoID(i int64) *PRNotificationCreate {
	pnc.mutation.SetRepoID(i)
	return pnc
}

// SetPullRequestID sets the "pull_request_id" field.
func (pnc *PRNotificationCreate) SetPullRequestID(i int) *PRNotificationCreate {
	pnc.mutation.SetPullRequestID(i)
	return pnc
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (pnc *PRNotificationCreate) SetPullRequestTitle(s string) *PRNotificationCreate {
	pnc.mutation.SetPullRequestTitle(s)
	return pnc
}

// SetNillablePullRequestTitle sets the "pull_request_title" field if the given value is not nil.
func (pnc *PRNotificationCreate) SetNillablePullRequestTitle(s *string) *PRNotificationCreate {
	if s != nil {
		pnc.SetPullRequestTitle(*s)
	}
	return pnc
}

// SetPullRequestBody sets the "pull_request_body" field.
func (pnc *PRNotificationCreate) SetPullRequestBody(s string) *PRNotificationCreate {
	pnc.mutation.SetPullRequestBody(s)
	return pnc
}

// SetNillablePullRequestBody sets the "pull_request_body" field if the given value is not nil.
func (pnc *PRNotificationCreate) SetNillablePullRequestBody(s *string) *PRNotificationCreate {
	if s != nil {
		pnc.SetPullRequestBody(*s)
	}
	return pnc
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (pnc *PRNotificationCreate) SetPullRequestAuthorLogin(s string) *PRNotificationCreate {
	pnc.mutation.SetPullRequestAuthorLogin(s)
	return pnc
}

// SetNillablePullRequestAuthorLogin sets the "pull_request_author_login" field if the given value is not nil.
func (pnc *PRNotificationCreate) SetNillablePullRequestAuthorLogin(s *string) *PRNotificationCreate {
	if s != nil {
		pnc.SetPullRequestAuthorLogin(*s)
	}
	return pnc
}

// SetMessageID sets the "message_id" field.
func (pnc *PRNotificationCreate) SetMessageID(i int) *PRNotificationCreate {
	pnc.mutation.SetMessageID(i)
	return pnc
}

// Mutation returns the PRNotificationMutation object of the builder.
func (pnc *PRNotificationCreate) Mutation() *PRNotificationMutation {
	return pnc.mutation
}

// Save creates the PRNotification in the database.
func (pnc *PRNotificationCreate) Save(ctx context.Context) (*PRNotification, error) {
	pnc.defaults()
	return withHooks(ctx, pnc.sqlSave, pnc.mutation, pnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pnc *PRNotificationCreate) SaveX(ctx context.Context) *PRNotification {
	v, err := pnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pnc *PRNotificationCreate) Exec(ctx context.Context) error {
	_, err := pnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pnc *PRNotificationCreate) ExecX(ctx context.Context) {
	if err := pnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pnc *PRNotificationCreate) defaults() {
	if _, ok := pnc.mutation.PullRequestTitle(); !ok {
		v := prnotification.DefaultPullRequestTitle
		pnc.mutation.SetPullRequestTitle(v)
	}
	if _, ok := pnc.mutation.PullRequestBody(); !ok {
		v := prnotification.DefaultPullRequestBody
		pnc.mutation.SetPullRequestBody(v)
	}
	if _, ok := pnc.mutation.PullRequestAuthorLogin(); !ok {
		v := prnotification.DefaultPullRequestAuthorLogin
		pnc.mutation.SetPullRequestAuthorLogin(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pnc *PRNotificationCreate) check() error {
	if _, ok := pnc.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "PRNotification.repo_id"`)}
	}
	if _, ok := pnc.mutation.PullRequestID(); !ok {
		return &ValidationError{Name: "pull_request_id", err: errors.New(`ent: missing required field "PRNotification.pull_request_id"`)}
	}
	if _, ok := pnc.mutation.PullRequestTitle(); !ok {
		return &ValidationError{Name: "pull_request_title", err: errors.New(`ent: missing required field "PRNotification.pull_request_title"`)}
	}
	if _, ok := pnc.mutation.PullRequestBody(); !ok {
		return &ValidationError{Name: "pull_request_body", err: errors.New(`ent: missing required field "PRNotification.pull_request_body"`)}
	}
	if _, ok := pnc.mutation.PullRequestAuthorLogin(); !ok {
		return &ValidationError{Name: "pull_request_author_login", err: errors.New(`ent: missing required field "PRNotification.pull_request_author_login"`)}
	}
	if _, ok := pnc.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "PRNotification.message_id"`)}
	}
	return nil
}

func (pnc *PRNotificationCreate) sqlSave(ctx context.Context) (*PRNotification, error) {
	if err := pnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pnc.mutation.id = &_node.ID
	pnc.mutation.done = true
	return _node, nil
}

func (pnc *PRNotificationCreate) createSpec() (*PRNotification, *sqlgraph.CreateSpec) {
	var (
		_node = &PRNotification{config: pnc.config}
		_spec = sqlgraph.NewCreateSpec(prnotification.Table, sqlgraph.NewFieldSpec(prnotification.FieldID, field.TypeInt))
	)
	_spec.OnConflict = pnc.conflict
	if value, ok := pnc.mutation.RepoID(); ok {
		_spec.SetField(prnotification.FieldRepoID, field.TypeInt64, value)
		_node.RepoID = value
	}
	if value, ok := pnc.mutation.PullRequestID(); ok {
		_spec.SetField(prnotification.FieldPullRequestID, field.TypeInt, value)
		_node.PullRequestID = value
	}
	if value, ok := pnc.mutation.PullRequestTitle(); ok {
		_spec.SetField(prnotification.FieldPullRequestTitle, field.TypeString, value)
		_node.PullRequestTitle = value
	}
	if value, ok := pnc.mutation.PullRequestBody(); ok {
		_spec.SetField(prnotification.FieldPullRequestBody, field.TypeString, value)
		_node.PullRequestBody = value
	}
	if value, ok := pnc.mutation.PullRequestAuthorLogin(); ok {
		_spec.SetField(prnotification.FieldPullRequestAuthorLogin, field.TypeString, value)
		_node.PullRequestAuthorLogin = value
	}
	if value, ok := pnc.mutation.MessageID(); ok {
		_spec.SetField(prnotification.FieldMessageID, field.TypeInt, value)
		_node.MessageID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PRNotification.Create().
//		SetRepoID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PRNotificationUpsert) {
//			SetRepoID(v+v).
//		}).
//		Exec(ctx)
func (pnc *PRNotificationCreate) OnConflict(opts ...sql.ConflictOption) *PRNotificationUpsertOne {
	pnc.conflict = opts
	return &PRNotificationUpsertOne{
		create: pnc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pnc *PRNotificationCreate) OnConflictColumns(columns ...string) *PRNotificationUpsertOne {
	pnc.conflict = append(pnc.conflict, sql.ConflictColumns(columns...))
	return &PRNotificationUpsertOne{
		create: pnc,
	}
}

type (
	// PRNotificationUpsertOne is the builder for "upsert"-ing
	//  one PRNotification node.
	PRNotificationUpsertOne struct {
		create *PRNotificationCreate
	}

	// PRNotificationUpsert is the "OnConflict" setter.
	PRNotificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetRepoID sets the "repo_id" field.
func (u *PRNotificationUpsert) SetRepoID(v int64) *PRNotificationUpsert {
	u.Set(prnotification.FieldRepoID, v)
	return u
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdateRepoID() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldRepoID)
	return u
}

// AddRepoID adds v to the "repo_id" field.
func (u *PRNotificationUpsert) AddRepoID(v int64) *PRNotificationUpsert {
	u.Add(prnotification.FieldRepoID, v)
	return u
}

// SetPullRequestID sets the "pull_request_id" field.
func (u *PRNotificationUpsert) SetPullRequestID(v int) *PRNotificationUpsert {
	u.Set(prnotification.FieldPullRequestID, v)
	return u
}

// UpdatePullRequestID sets the "pull_request_id" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdatePullRequestID() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldPullRequestID)
	return u
}

// AddPullRequestID adds v to the "pull_request_id" field.
func (u *PRNotificationUpsert) AddPullRequestID(v int) *PRNotificationUpsert {
	u.Add(prnotification.FieldPullRequestID, v)
	return u
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (u *PRNotificationUpsert) SetPullRequestTitle(v string) *PRNotificationUpsert {
	u.Set(prnotification.FieldPullRequestTitle, v)
	return u
}

// UpdatePullRequestTitle sets the "pull_request_title" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdatePullRequestTitle() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldPullRequestTitle)
	return u
}

// SetPullRequestBody sets the "pull_request_body" field.
func (u *PRNotificationUpsert) SetPullRequestBody(v string) *PRNotificationUpsert {
	u.Set(prnotification.FieldPullRequestBody, v)
	return u
}

// UpdatePullRequestBody sets the "pull_request_body" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdatePullRequestBody() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldPullRequestBody)
	return u
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (u *PRNotificationUpsert) SetPullRequestAuthorLogin(v string) *PRNotificationUpsert {
	u.Set(prnotification.FieldPullRequestAuthorLogin, v)
	return u
}

// UpdatePullRequestAuthorLogin sets the "pull_request_author_login" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdatePullRequestAuthorLogin() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldPullRequestAuthorLogin)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *PRNotificationUpsert) SetMessageID(v int) *PRNotificationUpsert {
	u.Set(prnotification.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *PRNotificationUpsert) UpdateMessageID() *PRNotificationUpsert {
	u.SetExcluded(prnotification.FieldMessageID)
	return u
}

// AddMessageID adds v to the "message_id" field.
func (u *PRNotificationUpsert) AddMessageID(v int) *PRNotificationUpsert {
	u.Add(prnotification.FieldMessageID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PRNotificationUpsertOne) UpdateNewValues() *PRNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PRNotificationUpsertOne) Ignore() *PRNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PRNotificationUpsertOne) DoNothing() *PRNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PRNotificationCreate.OnConflict
// documentation for more info.
func (u *PRNotificationUpsertOne) Update(set func(*PRNotificationUpsert)) *PRNotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PRNotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRepoID sets the "repo_id" field.
func (u *PRNotificationUpsertOne) SetRepoID(v int64) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetRepoID(v)
	})
}

// AddRepoID adds v to the "repo_id" field.
func (u *PRNotificationUpsertOne) AddRepoID(v int64) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdateRepoID() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdateRepoID()
	})
}

// SetPullRequestID sets the "pull_request_id" field.
func (u *PRNotificationUpsertOne) SetPullRequestID(v int) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestID(v)
	})
}

// AddPullRequestID adds v to the "pull_request_id" field.
func (u *PRNotificationUpsertOne) AddPullRequestID(v int) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddPullRequestID(v)
	})
}

// UpdatePullRequestID sets the "pull_request_id" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdatePullRequestID() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestID()
	})
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (u *PRNotificationUpsertOne) SetPullRequestTitle(v string) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestTitle(v)
	})
}

// UpdatePullRequestTitle sets the "pull_request_title" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdatePullRequestTitle() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestTitle()
	})
}

// SetPullRequestBody sets the "pull_request_body" field.
func (u *PRNotificationUpsertOne) SetPullRequestBody(v string) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestBody(v)
	})
}

// UpdatePullRequestBody sets the "pull_request_body" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdatePullRequestBody() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestBody()
	})
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (u *PRNotificationUpsertOne) SetPullRequestAuthorLogin(v string) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestAuthorLogin(v)
	})
}

// UpdatePullRequestAuthorLogin sets the "pull_request_author_login" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdatePullRequestAuthorLogin() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestAuthorLogin()
	})
}

// SetMessageID sets the "message_id" field.
func (u *PRNotificationUpsertOne) SetMessageID(v int) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *PRNotificationUpsertOne) AddMessageID(v int) *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *PRNotificationUpsertOne) UpdateMessageID() *PRNotificationUpsertOne {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdateMessageID()
	})
}

// Exec executes the query.
func (u *PRNotificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PRNotificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PRNotificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PRNotificationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PRNotificationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PRNotificationCreateBulk is the builder for creating many PRNotification entities in bulk.
type PRNotificationCreateBulk struct {
	config
	err      error
	builders []*PRNotificationCreate
	conflict []sql.ConflictOption
}

// Save creates the PRNotification entities in the database.
func (pncb *PRNotificationCreateBulk) Save(ctx context.Context) ([]*PRNotification, error) {
	if pncb.err != nil {
		return nil, pncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pncb.builders))
	nodes := make([]*PRNotification, len(pncb.builders))
	mutators := make([]Mutator, len(pncb.builders))
	for i := range pncb.builders {
		func(i int, root context.Context) {
			builder := pncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PRNotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pncb *PRNotificationCreateBulk) SaveX(ctx context.Context) []*PRNotification {
	v, err := pncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pncb *PRNotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := pncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pncb *PRNotificationCreateBulk) ExecX(ctx context.Context) {
	if err := pncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PRNotification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PRNotificationUpsert) {
//			SetRepoID(v+v).
//		}).
//		Exec(ctx)
func (pncb *PRNotificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PRNotificationUpsertBulk {
	pncb.conflict = opts
	return &PRNotificationUpsertBulk{
		create: pncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pncb *PRNotificationCreateBulk) OnConflictColumns(columns ...string) *PRNotificationUpsertBulk {
	pncb.conflict = append(pncb.conflict, sql.ConflictColumns(columns...))
	return &PRNotificationUpsertBulk{
		create: pncb,
	}
}

// PRNotificationUpsertBulk is the builder for "upsert"-ing
// a bulk of PRNotification nodes.
type PRNotificationUpsertBulk struct {
	create *PRNotificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PRNotificationUpsertBulk) UpdateNewValues() *PRNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PRNotification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PRNotificationUpsertBulk) Ignore() *PRNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PRNotificationUpsertBulk) DoNothing() *PRNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PRNotificationCreateBulk.OnConflict
// documentation for more info.
func (u *PRNotificationUpsertBulk) Update(set func(*PRNotificationUpsert)) *PRNotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PRNotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRepoID sets the "repo_id" field.
func (u *PRNotificationUpsertBulk) SetRepoID(v int64) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetRepoID(v)
	})
}

// AddRepoID adds v to the "repo_id" field.
func (u *PRNotificationUpsertBulk) AddRepoID(v int64) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdateRepoID() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdateRepoID()
	})
}

// SetPullRequestID sets the "pull_request_id" field.
func (u *PRNotificationUpsertBulk) SetPullRequestID(v int) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestID(v)
	})
}

// AddPullRequestID adds v to the "pull_request_id" field.
func (u *PRNotificationUpsertBulk) AddPullRequestID(v int) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddPullRequestID(v)
	})
}

// UpdatePullRequestID sets the "pull_request_id" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdatePullRequestID() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestID()
	})
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (u *PRNotificationUpsertBulk) SetPullRequestTitle(v string) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestTitle(v)
	})
}

// UpdatePullRequestTitle sets the "pull_request_title" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdatePullRequestTitle() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestTitle()
	})
}

// SetPullRequestBody sets the "pull_request_body" field.
func (u *PRNotificationUpsertBulk) SetPullRequestBody(v string) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestBody(v)
	})
}

// UpdatePullRequestBody sets the "pull_request_body" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdatePullRequestBody() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestBody()
	})
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (u *PRNotificationUpsertBulk) SetPullRequestAuthorLogin(v string) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetPullRequestAuthorLogin(v)
	})
}

// UpdatePullRequestAuthorLogin sets the "pull_request_author_login" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdatePullRequestAuthorLogin() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdatePullRequestAuthorLogin()
	})
}

// SetMessageID sets the "message_id" field.
func (u *PRNotificationUpsertBulk) SetMessageID(v int) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.SetMessageID(v)
	})
}

// AddMessageID adds v to the "message_id" field.
func (u *PRNotificationUpsertBulk) AddMessageID(v int) *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.AddMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *PRNotificationUpsertBulk) UpdateMessageID() *PRNotificationUpsertBulk {
	return u.Update(func(s *PRNotificationUpsert) {
		s.UpdateMessageID()
	})
}

// Exec executes the query.
func (u *PRNotificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PRNotificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PRNotificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PRNotificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
