// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/predicate"
	"github.com/go-faster/bot/internal/ent/prnotification"
)

// PRNotificationQuery is the builder for querying PRNotification entities.
type PRNotificationQuery struct {
	config
	ctx        *QueryContext
	order      []prnotification.Order
	inters     []Interceptor
	predicates []predicate.PRNotification
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PRNotificationQuery builder.
func (pnq *PRNotificationQuery) Where(ps ...predicate.PRNotification) *PRNotificationQuery {
	pnq.predicates = append(pnq.predicates, ps...)
	return pnq
}

// Limit the number of records to be returned by this query.
func (pnq *PRNotificationQuery) Limit(limit int) *PRNotificationQuery {
	pnq.ctx.Limit = &limit
	return pnq
}

// Offset to start from.
func (pnq *PRNotificationQuery) Offset(offset int) *PRNotificationQuery {
	pnq.ctx.Offset = &offset
	return pnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pnq *PRNotificationQuery) Unique(unique bool) *PRNotificationQuery {
	pnq.ctx.Unique = &unique
	return pnq
}

// Order specifies how the records should be ordered.
func (pnq *PRNotificationQuery) Order(o ...prnotification.Order) *PRNotificationQuery {
	pnq.order = append(pnq.order, o...)
	return pnq
}

// First returns the first PRNotification entity from the query.
// Returns a *NotFoundError when no PRNotification was found.
func (pnq *PRNotificationQuery) First(ctx context.Context) (*PRNotification, error) {
	nodes, err := pnq.Limit(1).All(setContextOp(ctx, pnq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prnotification.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pnq *PRNotificationQuery) FirstX(ctx context.Context) *PRNotification {
	node, err := pnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PRNotification ID from the query.
// Returns a *NotFoundError when no PRNotification ID was found.
func (pnq *PRNotificationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pnq.Limit(1).IDs(setContextOp(ctx, pnq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prnotification.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pnq *PRNotificationQuery) FirstIDX(ctx context.Context) int {
	id, err := pnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PRNotification entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PRNotification entity is found.
// Returns a *NotFoundError when no PRNotification entities are found.
func (pnq *PRNotificationQuery) Only(ctx context.Context) (*PRNotification, error) {
	nodes, err := pnq.Limit(2).All(setContextOp(ctx, pnq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prnotification.Label}
	default:
		return nil, &NotSingularError{prnotification.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pnq *PRNotificationQuery) OnlyX(ctx context.Context) *PRNotification {
	node, err := pnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PRNotification ID in the query.
// Returns a *NotSingularError when more than one PRNotification ID is found.
// Returns a *NotFoundError when no entities are found.
func (pnq *PRNotificationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pnq.Limit(2).IDs(setContextOp(ctx, pnq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prnotification.Label}
	default:
		err = &NotSingularError{prnotification.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pnq *PRNotificationQuery) OnlyIDX(ctx context.Context) int {
	id, err := pnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PRNotifications.
func (pnq *PRNotificationQuery) All(ctx context.Context) ([]*PRNotification, error) {
	ctx = setContextOp(ctx, pnq.ctx, "All")
	if err := pnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PRNotification, *PRNotificationQuery]()
	return withInterceptors[[]*PRNotification](ctx, pnq, qr, pnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pnq *PRNotificationQuery) AllX(ctx context.Context) []*PRNotification {
	nodes, err := pnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PRNotification IDs.
func (pnq *PRNotificationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pnq.ctx.Unique == nil && pnq.path != nil {
		pnq.Unique(true)
	}
	ctx = setContextOp(ctx, pnq.ctx, "IDs")
	if err = pnq.Select(prnotification.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pnq *PRNotificationQuery) IDsX(ctx context.Context) []int {
	ids, err := pnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pnq *PRNotificationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pnq.ctx, "Count")
	if err := pnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pnq, querierCount[*PRNotificationQuery](), pnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pnq *PRNotificationQuery) CountX(ctx context.Context) int {
	count, err := pnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pnq *PRNotificationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pnq.ctx, "Exist")
	switch _, err := pnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pnq *PRNotificationQuery) ExistX(ctx context.Context) bool {
	exist, err := pnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PRNotificationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pnq *PRNotificationQuery) Clone() *PRNotificationQuery {
	if pnq == nil {
		return nil
	}
	return &PRNotificationQuery{
		config:     pnq.config,
		ctx:        pnq.ctx.Clone(),
		order:      append([]prnotification.Order{}, pnq.order...),
		inters:     append([]Interceptor{}, pnq.inters...),
		predicates: append([]predicate.PRNotification{}, pnq.predicates...),
		// clone intermediate query.
		sql:  pnq.sql.Clone(),
		path: pnq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RepoID int64 `json:"repo_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PRNotification.Query().
//		GroupBy(prnotification.FieldRepoID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pnq *PRNotificationQuery) GroupBy(field string, fields ...string) *PRNotificationGroupBy {
	pnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PRNotificationGroupBy{build: pnq}
	grbuild.flds = &pnq.ctx.Fields
	grbuild.label = prnotification.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RepoID int64 `json:"repo_id,omitempty"`
//	}
//
//	client.PRNotification.Query().
//		Select(prnotification.FieldRepoID).
//		Scan(ctx, &v)
func (pnq *PRNotificationQuery) Select(fields ...string) *PRNotificationSelect {
	pnq.ctx.Fields = append(pnq.ctx.Fields, fields...)
	sbuild := &PRNotificationSelect{PRNotificationQuery: pnq}
	sbuild.label = prnotification.Label
	sbuild.flds, sbuild.scan = &pnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PRNotificationSelect configured with the given aggregations.
func (pnq *PRNotificationQuery) Aggregate(fns ...AggregateFunc) *PRNotificationSelect {
	return pnq.Select().Aggregate(fns...)
}

func (pnq *PRNotificationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pnq); err != nil {
				return err
			}
		}
	}
	for _, f := range pnq.ctx.Fields {
		if !prnotification.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pnq.path != nil {
		prev, err := pnq.path(ctx)
		if err != nil {
			return err
		}
		pnq.sql = prev
	}
	return nil
}

func (pnq *PRNotificationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PRNotification, error) {
	var (
		nodes = []*PRNotification{}
		_spec = pnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PRNotification).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PRNotification{config: pnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pnq *PRNotificationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pnq.querySpec()
	_spec.Node.Columns = pnq.ctx.Fields
	if len(pnq.ctx.Fields) > 0 {
		_spec.Unique = pnq.ctx.Unique != nil && *pnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pnq.driver, _spec)
}

func (pnq *PRNotificationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(prnotification.Table, prnotification.Columns, sqlgraph.NewFieldSpec(prnotification.FieldID, field.TypeInt))
	_spec.From = pnq.sql
	if unique := pnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pnq.path != nil {
		_spec.Unique = true
	}
	if fields := pnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prnotification.FieldID)
		for i := range fields {
			if fields[i] != prnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pnq *PRNotificationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pnq.driver.Dialect())
	t1 := builder.Table(prnotification.Table)
	columns := pnq.ctx.Fields
	if len(columns) == 0 {
		columns = prnotification.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pnq.sql != nil {
		selector = pnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pnq.ctx.Unique != nil && *pnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pnq.predicates {
		p(selector)
	}
	for _, p := range pnq.order {
		p(selector)
	}
	if offset := pnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PRNotificationGroupBy is the group-by builder for PRNotification entities.
type PRNotificationGroupBy struct {
	selector
	build *PRNotificationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pngb *PRNotificationGroupBy) Aggregate(fns ...AggregateFunc) *PRNotificationGroupBy {
	pngb.fns = append(pngb.fns, fns...)
	return pngb
}

// Scan applies the selector query and scans the result into the given value.
func (pngb *PRNotificationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pngb.build.ctx, "GroupBy")
	if err := pngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PRNotificationQuery, *PRNotificationGroupBy](ctx, pngb.build, pngb, pngb.build.inters, v)
}

func (pngb *PRNotificationGroupBy) sqlScan(ctx context.Context, root *PRNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pngb.fns))
	for _, fn := range pngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pngb.flds)+len(pngb.fns))
		for _, f := range *pngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PRNotificationSelect is the builder for selecting fields of PRNotification entities.
type PRNotificationSelect struct {
	*PRNotificationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pns *PRNotificationSelect) Aggregate(fns ...AggregateFunc) *PRNotificationSelect {
	pns.fns = append(pns.fns, fns...)
	return pns
}

// Scan applies the selector query and scans the result into the given value.
func (pns *PRNotificationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pns.ctx, "Select")
	if err := pns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PRNotificationQuery, *PRNotificationSelect](ctx, pns.PRNotificationQuery, pns, pns.inters, v)
}

func (pns *PRNotificationSelect) sqlScan(ctx context.Context, root *PRNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pns.fns))
	for _, fn := range pns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
