// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/predicate"
	"github.com/go-faster/bot/internal/ent/prnotification"
)

// PRNotificationUpdate is the builder for updating PRNotification entities.
type PRNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *PRNotificationMutation
}

// Where appends a list predicates to the PRNotificationUpdate builder.
func (_u *PRNotificationUpdate) Where(ps ...predicate.PRNotification) *PRNotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *PRNotificationUpdate) SetRepoID(v int64) *PRNotificationUpdate {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillableRepoID(v *int64) *PRNotificationUpdate {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *PRNotificationUpdate) AddRepoID(v int64) *PRNotificationUpdate {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetPullRequestID sets the "pull_request_id" field.
func (_u *PRNotificationUpdate) SetPullRequestID(v int) *PRNotificationUpdate {
	_u.mutation.ResetPullRequestID()
	_u.mutation.SetPullRequestID(v)
	return _u
}

// SetNillablePullRequestID sets the "pull_request_id" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillablePullRequestID(v *int) *PRNotificationUpdate {
	if v != nil {
		_u.SetPullRequestID(*v)
	}
	return _u
}

// AddPullRequestID adds value to the "pull_request_id" field.
func (_u *PRNotificationUpdate) AddPullRequestID(v int) *PRNotificationUpdate {
	_u.mutation.AddPullRequestID(v)
	return _u
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (_u *PRNotificationUpdate) SetPullRequestTitle(v string) *PRNotificationUpdate {
	_u.mutation.SetPullRequestTitle(v)
	return _u
}

// SetNillablePullRequestTitle sets the "pull_request_title" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillablePullRequestTitle(v *string) *PRNotificationUpdate {
	if v != nil {
		_u.SetPullRequestTitle(*v)
	}
	return _u
}

// SetPullRequestBody sets the "pull_request_body" field.
func (_u *PRNotificationUpdate) SetPullRequestBody(v string) *PRNotificationUpdate {
	_u.mutation.SetPullRequestBody(v)
	return _u
}

// SetNillablePullRequestBody sets the "pull_request_body" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillablePullRequestBody(v *string) *PRNotificationUpdate {
	if v != nil {
		_u.SetPullRequestBody(*v)
	}
	return _u
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (_u *PRNotificationUpdate) SetPullRequestAuthorLogin(v string) *PRNotificationUpdate {
	_u.mutation.SetPullRequestAuthorLogin(v)
	return _u
}

// SetNillablePullRequestAuthorLogin sets the "pull_request_author_login" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillablePullRequestAuthorLogin(v *string) *PRNotificationUpdate {
	if v != nil {
		_u.SetPullRequestAuthorLogin(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *PRNotificationUpdate) SetMessageID(v int) *PRNotificationUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *PRNotificationUpdate) SetNillableMessageID(v *int) *PRNotificationUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *PRNotificationUpdate) AddMessageID(v int) *PRNotificationUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// Mutation returns the PRNotificationMutation object of the builder.
func (_u *PRNotificationUpdate) Mutation() *PRNotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PRNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PRNotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRNotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRNotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(prnotification.Table, prnotification.Columns, sqlgraph.NewFieldSpec(prnotification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(prnotification.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(prnotification.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PullRequestID(); ok {
		_spec.SetField(prnotification.FieldPullRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPullRequestID(); ok {
		_spec.AddField(prnotification.FieldPullRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PullRequestTitle(); ok {
		_spec.SetField(prnotification.FieldPullRequestTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PullRequestBody(); ok {
		_spec.SetField(prnotification.FieldPullRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.PullRequestAuthorLogin(); ok {
		_spec.SetField(prnotification.FieldPullRequestAuthorLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(prnotification.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(prnotification.FieldMessageID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PRNotificationUpdateOne is the builder for updating a single PRNotification entity.
type PRNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PRNotificationMutation
}

// SetRepoID sets the "repo_id" field.
func (_u *PRNotificationUpdateOne) SetRepoID(v int64) *PRNotificationUpdateOne {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillableRepoID(v *int64) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *PRNotificationUpdateOne) AddRepoID(v int64) *PRNotificationUpdateOne {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetPullRequestID sets the "pull_request_id" field.
func (_u *PRNotificationUpdateOne) SetPullRequestID(v int) *PRNotificationUpdateOne {
	_u.mutation.ResetPullRequestID()
	_u.mutation.SetPullRequestID(v)
	return _u
}

// SetNillablePullRequestID sets the "pull_request_id" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillablePullRequestID(v *int) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetPullRequestID(*v)
	}
	return _u
}

// AddPullRequestID adds value to the "pull_request_id" field.
func (_u *PRNotificationUpdateOne) AddPullRequestID(v int) *PRNotificationUpdateOne {
	_u.mutation.AddPullRequestID(v)
	return _u
}

// SetPullRequestTitle sets the "pull_request_title" field.
func (_u *PRNotificationUpdateOne) SetPullRequestTitle(v string) *PRNotificationUpdateOne {
	_u.mutation.SetPullRequestTitle(v)
	return _u
}

// SetNillablePullRequestTitle sets the "pull_request_title" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillablePullRequestTitle(v *string) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetPullRequestTitle(*v)
	}
	return _u
}

// SetPullRequestBody sets the "pull_request_body" field.
func (_u *PRNotificationUpdateOne) SetPullRequestBody(v string) *PRNotificationUpdateOne {
	_u.mutation.SetPullRequestBody(v)
	return _u
}

// SetNillablePullRequestBody sets the "pull_request_body" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillablePullRequestBody(v *string) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetPullRequestBody(*v)
	}
	return _u
}

// SetPullRequestAuthorLogin sets the "pull_request_author_login" field.
func (_u *PRNotificationUpdateOne) SetPullRequestAuthorLogin(v string) *PRNotificationUpdateOne {
	_u.mutation.SetPullRequestAuthorLogin(v)
	return _u
}

// SetNillablePullRequestAuthorLogin sets the "pull_request_author_login" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillablePullRequestAuthorLogin(v *string) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetPullRequestAuthorLogin(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *PRNotificationUpdateOne) SetMessageID(v int) *PRNotificationUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *PRNotificationUpdateOne) SetNillableMessageID(v *int) *PRNotificationUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *PRNotificationUpdateOne) AddMessageID(v int) *PRNotificationUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// Mutation returns the PRNotificationMutation object of the builder.
func (_u *PRNotificationUpdateOne) Mutation() *PRNotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PRNotificationUpdate builder.
func (_u *PRNotificationUpdateOne) Where(ps ...predicate.PRNotification) *PRNotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PRNotificationUpdateOne) Select(field string, fields ...string) *PRNotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PRNotification entity.
func (_u *PRNotificationUpdateOne) Save(ctx context.Context) (*PRNotification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PRNotificationUpdateOne) SaveX(ctx context.Context) *PRNotification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PRNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PRNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PRNotificationUpdateOne) sqlSave(ctx context.Context) (_node *PRNotification, err error) {
	_spec := sqlgraph.NewUpdateSpec(prnotification.Table, prnotification.Columns, sqlgraph.NewFieldSpec(prnotification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PRNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prnotification.FieldID)
		for _, f := range fields {
			if !prnotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(prnotification.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(prnotification.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PullRequestID(); ok {
		_spec.SetField(prnotification.FieldPullRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPullRequestID(); ok {
		_spec.AddField(prnotification.FieldPullRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PullRequestTitle(); ok {
		_spec.SetField(prnotification.FieldPullRequestTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PullRequestBody(); ok {
		_spec.SetField(prnotification.FieldPullRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.PullRequestAuthorLogin(); ok {
		_spec.SetField(prnotification.FieldPullRequestAuthorLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(prnotification.FieldMessageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(prnotification.FieldMessageID, field.TypeInt, value)
	}
	_node = &PRNotification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
