// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/telegramchannelstate"
	"github.com/go-faster/bot/internal/ent/telegramuserstate"
)

// TelegramChannelStateCreate is the builder for creating a TelegramChannelState entity.
type TelegramChannelStateCreate struct {
	config
	mutation *TelegramChannelStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetChannelID sets the "channel_id" field.
func (_c *TelegramChannelStateCreate) SetChannelID(v int64) *TelegramChannelStateCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TelegramChannelStateCreate) SetUserID(v int64) *TelegramChannelStateCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPts sets the "pts" field.
func (_c *TelegramChannelStateCreate) SetPts(v int) *TelegramChannelStateCreate {
	_c.mutation.SetPts(v)
	return _c
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (_c *TelegramChannelStateCreate) SetNillablePts(v *int) *TelegramChannelStateCreate {
	if v != nil {
		_c.SetPts(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the TelegramUserState entity.
func (_c *TelegramChannelStateCreate) SetUser(v *TelegramUserState) *TelegramChannelStateCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TelegramChannelStateMutation object of the builder.
func (_c *TelegramChannelStateCreate) Mutation() *TelegramChannelStateMutation {
	return _c.mutation
}

// Save creates the TelegramChannelState in the database.
func (_c *TelegramChannelStateCreate) Save(ctx context.Context) (*TelegramChannelState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TelegramChannelStateCreate) SaveX(ctx context.Context) *TelegramChannelState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramChannelStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramChannelStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TelegramChannelStateCreate) defaults() {
	if _, ok := _c.mutation.Pts(); !ok {
		v := telegramchannelstate.DefaultPts
		_c.mutation.SetPts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TelegramChannelStateCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "TelegramChannelState.channel_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TelegramChannelState.user_id"`)}
	}
	if _, ok := _c.mutation.Pts(); !ok {
		return &ValidationError{Name: "pts", err: errors.New(`ent: missing required field "TelegramChannelState.pts"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TelegramChannelState.user"`)}
	}
	return nil
}

func (_c *TelegramChannelStateCreate) sqlSave(ctx context.Context) (*TelegramChannelState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TelegramChannelStateCreate) createSpec() (*TelegramChannelState, *sqlgraph.CreateSpec) {
	var (
		_node = &TelegramChannelState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(telegramchannelstate.Table, sqlgraph.NewFieldSpec(telegramchannelstate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(telegramchannelstate.FieldChannelID, field.TypeInt64, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.Pts(); ok {
		_spec.SetField(telegramchannelstate.FieldPts, field.TypeInt, value)
		_node.Pts = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telegramchannelstate.UserTable,
			Columns: []string{telegramchannelstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramChannelState.Create().
//		SetChannelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramChannelStateUpsert) {
//			SetChannelID(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramChannelStateCreate) OnConflict(opts ...sql.ConflictOption) *TelegramChannelStateUpsertOne {
	_c.conflict = opts
	return &TelegramChannelStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramChannelStateCreate) OnConflictColumns(columns ...string) *TelegramChannelStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramChannelStateUpsertOne{
		create: _c,
	}
}

type (
	// TelegramChannelStateUpsertOne is the builder for "upsert"-ing
	//  one TelegramChannelState node.
	TelegramChannelStateUpsertOne struct {
		create *TelegramChannelStateCreate
	}

	// TelegramChannelStateUpsert is the "OnConflict" setter.
	TelegramChannelStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetChannelID sets the "channel_id" field.
func (u *TelegramChannelStateUpsert) SetChannelID(v int64) *TelegramChannelStateUpsert {
	u.Set(telegramchannelstate.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsert) UpdateChannelID() *TelegramChannelStateUpsert {
	u.SetExcluded(telegramchannelstate.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *TelegramChannelStateUpsert) AddChannelID(v int64) *TelegramChannelStateUpsert {
	u.Add(telegramchannelstate.FieldChannelID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TelegramChannelStateUpsert) SetUserID(v int64) *TelegramChannelStateUpsert {
	u.Set(telegramchannelstate.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsert) UpdateUserID() *TelegramChannelStateUpsert {
	u.SetExcluded(telegramchannelstate.FieldUserID)
	return u
}

// SetPts sets the "pts" field.
func (u *TelegramChannelStateUpsert) SetPts(v int) *TelegramChannelStateUpsert {
	u.Set(telegramchannelstate.FieldPts, v)
	return u
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramChannelStateUpsert) UpdatePts() *TelegramChannelStateUpsert {
	u.SetExcluded(telegramchannelstate.FieldPts)
	return u
}

// AddPts adds v to the "pts" field.
func (u *TelegramChannelStateUpsert) AddPts(v int) *TelegramChannelStateUpsert {
	u.Add(telegramchannelstate.FieldPts, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TelegramChannelStateUpsertOne) UpdateNewValues() *TelegramChannelStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TelegramChannelStateUpsertOne) Ignore() *TelegramChannelStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramChannelStateUpsertOne) DoNothing() *TelegramChannelStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramChannelStateCreate.OnConflict
// documentation for more info.
func (u *TelegramChannelStateUpsertOne) Update(set func(*TelegramChannelStateUpsert)) *TelegramChannelStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramChannelStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *TelegramChannelStateUpsertOne) SetChannelID(v int64) *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *TelegramChannelStateUpsertOne) AddChannelID(v int64) *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertOne) UpdateChannelID() *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdateChannelID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TelegramChannelStateUpsertOne) SetUserID(v int64) *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertOne) UpdateUserID() *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdateUserID()
	})
}

// SetPts sets the "pts" field.
func (u *TelegramChannelStateUpsertOne) SetPts(v int) *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetPts(v)
	})
}

// AddPts adds v to the "pts" field.
func (u *TelegramChannelStateUpsertOne) AddPts(v int) *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.AddPts(v)
	})
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertOne) UpdatePts() *TelegramChannelStateUpsertOne {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdatePts()
	})
}

// Exec executes the query.
func (u *TelegramChannelStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramChannelStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramChannelStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TelegramChannelStateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TelegramChannelStateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TelegramChannelStateCreateBulk is the builder for creating many TelegramChannelState entities in bulk.
type TelegramChannelStateCreateBulk struct {
	config
	err      error
	builders []*TelegramChannelStateCreate
	conflict []sql.ConflictOption
}

// Save creates the TelegramChannelState entities in the database.
func (_c *TelegramChannelStateCreateBulk) Save(ctx context.Context) ([]*TelegramChannelState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TelegramChannelState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TelegramChannelStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TelegramChannelStateCreateBulk) SaveX(ctx context.Context) []*TelegramChannelState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramChannelStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramChannelStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramChannelState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramChannelStateUpsert) {
//			SetChannelID(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramChannelStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *TelegramChannelStateUpsertBulk {
	_c.conflict = opts
	return &TelegramChannelStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramChannelStateCreateBulk) OnConflictColumns(columns ...string) *TelegramChannelStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramChannelStateUpsertBulk{
		create: _c,
	}
}

// TelegramChannelStateUpsertBulk is the builder for "upsert"-ing
// a bulk of TelegramChannelState nodes.
type TelegramChannelStateUpsertBulk struct {
	create *TelegramChannelStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TelegramChannelStateUpsertBulk) UpdateNewValues() *TelegramChannelStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramChannelState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TelegramChannelStateUpsertBulk) Ignore() *TelegramChannelStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramChannelStateUpsertBulk) DoNothing() *TelegramChannelStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramChannelStateCreateBulk.OnConflict
// documentation for more info.
func (u *TelegramChannelStateUpsertBulk) Update(set func(*TelegramChannelStateUpsert)) *TelegramChannelStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramChannelStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *TelegramChannelStateUpsertBulk) SetChannelID(v int64) *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *TelegramChannelStateUpsertBulk) AddChannelID(v int64) *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertBulk) UpdateChannelID() *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdateChannelID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TelegramChannelStateUpsertBulk) SetUserID(v int64) *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertBulk) UpdateUserID() *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdateUserID()
	})
}

// SetPts sets the "pts" field.
func (u *TelegramChannelStateUpsertBulk) SetPts(v int) *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.SetPts(v)
	})
}

// AddPts adds v to the "pts" field.
func (u *TelegramChannelStateUpsertBulk) AddPts(v int) *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.AddPts(v)
	})
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramChannelStateUpsertBulk) UpdatePts() *TelegramChannelStateUpsertBulk {
	return u.Update(func(s *TelegramChannelStateUpsert) {
		s.UpdatePts()
	})
}

// Exec executes the query.
func (u *TelegramChannelStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TelegramChannelStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramChannelStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramChannelStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
