// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/predicate"
	"github.com/go-faster/bot/internal/ent/telegramsession"
)

// TelegramSessionUpdate is the builder for updating TelegramSession entities.
type TelegramSessionUpdate struct {
	config
	hooks    []Hook
	mutation *TelegramSessionMutation
}

// Where appends a list predicates to the TelegramSessionUpdate builder.
func (tsu *TelegramSessionUpdate) Where(ps ...predicate.TelegramSession) *TelegramSessionUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetData sets the "data" field.
func (tsu *TelegramSessionUpdate) SetData(b []byte) *TelegramSessionUpdate {
	tsu.mutation.SetData(b)
	return tsu
}

// Mutation returns the TelegramSessionMutation object of the builder.
func (tsu *TelegramSessionUpdate) Mutation() *TelegramSessionMutation {
	return tsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TelegramSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, TelegramSessionMutation](ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TelegramSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TelegramSessionUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TelegramSessionUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tsu *TelegramSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(telegramsession.Table, telegramsession.Columns, sqlgraph.NewFieldSpec(telegramsession.FieldID, field.TypeUUID))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.Data(); ok {
		_spec.SetField(telegramsession.FieldData, field.TypeBytes, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TelegramSessionUpdateOne is the builder for updating a single TelegramSession entity.
type TelegramSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TelegramSessionMutation
}

// SetData sets the "data" field.
func (tsuo *TelegramSessionUpdateOne) SetData(b []byte) *TelegramSessionUpdateOne {
	tsuo.mutation.SetData(b)
	return tsuo
}

// Mutation returns the TelegramSessionMutation object of the builder.
func (tsuo *TelegramSessionUpdateOne) Mutation() *TelegramSessionMutation {
	return tsuo.mutation
}

// Where appends a list predicates to the TelegramSessionUpdate builder.
func (tsuo *TelegramSessionUpdateOne) Where(ps ...predicate.TelegramSession) *TelegramSessionUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TelegramSessionUpdateOne) Select(field string, fields ...string) *TelegramSessionUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TelegramSession entity.
func (tsuo *TelegramSessionUpdateOne) Save(ctx context.Context) (*TelegramSession, error) {
	return withHooks[*TelegramSession, TelegramSessionMutation](ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TelegramSessionUpdateOne) SaveX(ctx context.Context) *TelegramSession {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TelegramSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TelegramSessionUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tsuo *TelegramSessionUpdateOne) sqlSave(ctx context.Context) (_node *TelegramSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(telegramsession.Table, telegramsession.Columns, sqlgraph.NewFieldSpec(telegramsession.FieldID, field.TypeUUID))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TelegramSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramsession.FieldID)
		for _, f := range fields {
			if !telegramsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != telegramsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.Data(); ok {
		_spec.SetField(telegramsession.FieldData, field.TypeBytes, value)
	}
	_node = &TelegramSession{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
