// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/telegramchannelstate"
	"github.com/go-faster/bot/internal/ent/telegramuserstate"
)

// TelegramUserStateCreate is the builder for creating a TelegramUserState entity.
type TelegramUserStateCreate struct {
	config
	mutation *TelegramUserStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQts sets the "qts" field.
func (_c *TelegramUserStateCreate) SetQts(v int) *TelegramUserStateCreate {
	_c.mutation.SetQts(v)
	return _c
}

// SetNillableQts sets the "qts" field if the given value is not nil.
func (_c *TelegramUserStateCreate) SetNillableQts(v *int) *TelegramUserStateCreate {
	if v != nil {
		_c.SetQts(*v)
	}
	return _c
}

// SetPts sets the "pts" field.
func (_c *TelegramUserStateCreate) SetPts(v int) *TelegramUserStateCreate {
	_c.mutation.SetPts(v)
	return _c
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (_c *TelegramUserStateCreate) SetNillablePts(v *int) *TelegramUserStateCreate {
	if v != nil {
		_c.SetPts(*v)
	}
	return _c
}

// SetDate sets the "date" field.
func (_c *TelegramUserStateCreate) SetDate(v int) *TelegramUserStateCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_c *TelegramUserStateCreate) SetNillableDate(v *int) *TelegramUserStateCreate {
	if v != nil {
		_c.SetDate(*v)
	}
	return _c
}

// SetSeq sets the "seq" field.
func (_c *TelegramUserStateCreate) SetSeq(v int) *TelegramUserStateCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_c *TelegramUserStateCreate) SetNillableSeq(v *int) *TelegramUserStateCreate {
	if v != nil {
		_c.SetSeq(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TelegramUserStateCreate) SetID(v int64) *TelegramUserStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddChannelIDs adds the "channels" edge to the TelegramChannelState entity by IDs.
func (_c *TelegramUserStateCreate) AddChannelIDs(ids ...int) *TelegramUserStateCreate {
	_c.mutation.AddChannelIDs(ids...)
	return _c
}

// AddChannels adds the "channels" edges to the TelegramChannelState entity.
func (_c *TelegramUserStateCreate) AddChannels(v ...*TelegramChannelState) *TelegramUserStateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChannelIDs(ids...)
}

// Mutation returns the TelegramUserStateMutation object of the builder.
func (_c *TelegramUserStateCreate) Mutation() *TelegramUserStateMutation {
	return _c.mutation
}

// Save creates the TelegramUserState in the database.
func (_c *TelegramUserStateCreate) Save(ctx context.Context) (*TelegramUserState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TelegramUserStateCreate) SaveX(ctx context.Context) *TelegramUserState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramUserStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramUserStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TelegramUserStateCreate) defaults() {
	if _, ok := _c.mutation.Qts(); !ok {
		v := telegramuserstate.DefaultQts
		_c.mutation.SetQts(v)
	}
	if _, ok := _c.mutation.Pts(); !ok {
		v := telegramuserstate.DefaultPts
		_c.mutation.SetPts(v)
	}
	if _, ok := _c.mutation.Date(); !ok {
		v := telegramuserstate.DefaultDate
		_c.mutation.SetDate(v)
	}
	if _, ok := _c.mutation.Seq(); !ok {
		v := telegramuserstate.DefaultSeq
		_c.mutation.SetSeq(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TelegramUserStateCreate) check() error {
	if _, ok := _c.mutation.Qts(); !ok {
		return &ValidationError{Name: "qts", err: errors.New(`ent: missing required field "TelegramUserState.qts"`)}
	}
	if _, ok := _c.mutation.Pts(); !ok {
		return &ValidationError{Name: "pts", err: errors.New(`ent: missing required field "TelegramUserState.pts"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "TelegramUserState.date"`)}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "TelegramUserState.seq"`)}
	}
	return nil
}

func (_c *TelegramUserStateCreate) sqlSave(ctx context.Context) (*TelegramUserState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TelegramUserStateCreate) createSpec() (*TelegramUserState, *sqlgraph.CreateSpec) {
	var (
		_node = &TelegramUserState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(telegramuserstate.Table, sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Qts(); ok {
		_spec.SetField(telegramuserstate.FieldQts, field.TypeInt, value)
		_node.Qts = value
	}
	if value, ok := _c.mutation.Pts(); ok {
		_spec.SetField(telegramuserstate.FieldPts, field.TypeInt, value)
		_node.Pts = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(telegramuserstate.FieldDate, field.TypeInt, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(telegramuserstate.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if nodes := _c.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   telegramuserstate.ChannelsTable,
			Columns: []string{telegramuserstate.ChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramchannelstate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramUserState.Create().
//		SetQts(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramUserStateUpsert) {
//			SetQts(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramUserStateCreate) OnConflict(opts ...sql.ConflictOption) *TelegramUserStateUpsertOne {
	_c.conflict = opts
	return &TelegramUserStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramUserStateCreate) OnConflictColumns(columns ...string) *TelegramUserStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramUserStateUpsertOne{
		create: _c,
	}
}

type (
	// TelegramUserStateUpsertOne is the builder for "upsert"-ing
	//  one TelegramUserState node.
	TelegramUserStateUpsertOne struct {
		create *TelegramUserStateCreate
	}

	// TelegramUserStateUpsert is the "OnConflict" setter.
	TelegramUserStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetQts sets the "qts" field.
func (u *TelegramUserStateUpsert) SetQts(v int) *TelegramUserStateUpsert {
	u.Set(telegramuserstate.FieldQts, v)
	return u
}

// UpdateQts sets the "qts" field to the value that was provided on create.
func (u *TelegramUserStateUpsert) UpdateQts() *TelegramUserStateUpsert {
	u.SetExcluded(telegramuserstate.FieldQts)
	return u
}

// AddQts adds v to the "qts" field.
func (u *TelegramUserStateUpsert) AddQts(v int) *TelegramUserStateUpsert {
	u.Add(telegramuserstate.FieldQts, v)
	return u
}

// SetPts sets the "pts" field.
func (u *TelegramUserStateUpsert) SetPts(v int) *TelegramUserStateUpsert {
	u.Set(telegramuserstate.FieldPts, v)
	return u
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramUserStateUpsert) UpdatePts() *TelegramUserStateUpsert {
	u.SetExcluded(telegramuserstate.FieldPts)
	return u
}

// AddPts adds v to the "pts" field.
func (u *TelegramUserStateUpsert) AddPts(v int) *TelegramUserStateUpsert {
	u.Add(telegramuserstate.FieldPts, v)
	return u
}

// SetDate sets the "date" field.
func (u *TelegramUserStateUpsert) SetDate(v int) *TelegramUserStateUpsert {
	u.Set(telegramuserstate.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *TelegramUserStateUpsert) UpdateDate() *TelegramUserStateUpsert {
	u.SetExcluded(telegramuserstate.FieldDate)
	return u
}

// AddDate adds v to the "date" field.
func (u *TelegramUserStateUpsert) AddDate(v int) *TelegramUserStateUpsert {
	u.Add(telegramuserstate.FieldDate, v)
	return u
}

// SetSeq sets the "seq" field.
func (u *TelegramUserStateUpsert) SetSeq(v int) *TelegramUserStateUpsert {
	u.Set(telegramuserstate.FieldSeq, v)
	return u
}

// UpdateSeq sets the "seq" field to the value that was provided on create.
func (u *TelegramUserStateUpsert) UpdateSeq() *TelegramUserStateUpsert {
	u.SetExcluded(telegramuserstate.FieldSeq)
	return u
}

// AddSeq adds v to the "seq" field.
func (u *TelegramUserStateUpsert) AddSeq(v int) *TelegramUserStateUpsert {
	u.Add(telegramuserstate.FieldSeq, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(telegramuserstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TelegramUserStateUpsertOne) UpdateNewValues() *TelegramUserStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(telegramuserstate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TelegramUserStateUpsertOne) Ignore() *TelegramUserStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramUserStateUpsertOne) DoNothing() *TelegramUserStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramUserStateCreate.OnConflict
// documentation for more info.
func (u *TelegramUserStateUpsertOne) Update(set func(*TelegramUserStateUpsert)) *TelegramUserStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramUserStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetQts sets the "qts" field.
func (u *TelegramUserStateUpsertOne) SetQts(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetQts(v)
	})
}

// AddQts adds v to the "qts" field.
func (u *TelegramUserStateUpsertOne) AddQts(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddQts(v)
	})
}

// UpdateQts sets the "qts" field to the value that was provided on create.
func (u *TelegramUserStateUpsertOne) UpdateQts() *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateQts()
	})
}

// SetPts sets the "pts" field.
func (u *TelegramUserStateUpsertOne) SetPts(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetPts(v)
	})
}

// AddPts adds v to the "pts" field.
func (u *TelegramUserStateUpsertOne) AddPts(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddPts(v)
	})
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramUserStateUpsertOne) UpdatePts() *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdatePts()
	})
}

// SetDate sets the "date" field.
func (u *TelegramUserStateUpsertOne) SetDate(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetDate(v)
	})
}

// AddDate adds v to the "date" field.
func (u *TelegramUserStateUpsertOne) AddDate(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *TelegramUserStateUpsertOne) UpdateDate() *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateDate()
	})
}

// SetSeq sets the "seq" field.
func (u *TelegramUserStateUpsertOne) SetSeq(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetSeq(v)
	})
}

// AddSeq adds v to the "seq" field.
func (u *TelegramUserStateUpsertOne) AddSeq(v int) *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddSeq(v)
	})
}

// UpdateSeq sets the "seq" field to the value that was provided on create.
func (u *TelegramUserStateUpsertOne) UpdateSeq() *TelegramUserStateUpsertOne {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateSeq()
	})
}

// Exec executes the query.
func (u *TelegramUserStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramUserStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramUserStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TelegramUserStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TelegramUserStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TelegramUserStateCreateBulk is the builder for creating many TelegramUserState entities in bulk.
type TelegramUserStateCreateBulk struct {
	config
	err      error
	builders []*TelegramUserStateCreate
	conflict []sql.ConflictOption
}

// Save creates the TelegramUserState entities in the database.
func (_c *TelegramUserStateCreateBulk) Save(ctx context.Context) ([]*TelegramUserState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TelegramUserState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TelegramUserStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TelegramUserStateCreateBulk) SaveX(ctx context.Context) []*TelegramUserState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramUserStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramUserStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramUserState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramUserStateUpsert) {
//			SetQts(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramUserStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *TelegramUserStateUpsertBulk {
	_c.conflict = opts
	return &TelegramUserStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramUserStateCreateBulk) OnConflictColumns(columns ...string) *TelegramUserStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramUserStateUpsertBulk{
		create: _c,
	}
}

// TelegramUserStateUpsertBulk is the builder for "upsert"-ing
// a bulk of TelegramUserState nodes.
type TelegramUserStateUpsertBulk struct {
	create *TelegramUserStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(telegramuserstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TelegramUserStateUpsertBulk) UpdateNewValues() *TelegramUserStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(telegramuserstate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramUserState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TelegramUserStateUpsertBulk) Ignore() *TelegramUserStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramUserStateUpsertBulk) DoNothing() *TelegramUserStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramUserStateCreateBulk.OnConflict
// documentation for more info.
func (u *TelegramUserStateUpsertBulk) Update(set func(*TelegramUserStateUpsert)) *TelegramUserStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramUserStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetQts sets the "qts" field.
func (u *TelegramUserStateUpsertBulk) SetQts(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetQts(v)
	})
}

// AddQts adds v to the "qts" field.
func (u *TelegramUserStateUpsertBulk) AddQts(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddQts(v)
	})
}

// UpdateQts sets the "qts" field to the value that was provided on create.
func (u *TelegramUserStateUpsertBulk) UpdateQts() *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateQts()
	})
}

// SetPts sets the "pts" field.
func (u *TelegramUserStateUpsertBulk) SetPts(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetPts(v)
	})
}

// AddPts adds v to the "pts" field.
func (u *TelegramUserStateUpsertBulk) AddPts(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddPts(v)
	})
}

// UpdatePts sets the "pts" field to the value that was provided on create.
func (u *TelegramUserStateUpsertBulk) UpdatePts() *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdatePts()
	})
}

// SetDate sets the "date" field.
func (u *TelegramUserStateUpsertBulk) SetDate(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetDate(v)
	})
}

// AddDate adds v to the "date" field.
func (u *TelegramUserStateUpsertBulk) AddDate(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *TelegramUserStateUpsertBulk) UpdateDate() *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateDate()
	})
}

// SetSeq sets the "seq" field.
func (u *TelegramUserStateUpsertBulk) SetSeq(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.SetSeq(v)
	})
}

// AddSeq adds v to the "seq" field.
func (u *TelegramUserStateUpsertBulk) AddSeq(v int) *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.AddSeq(v)
	})
}

// UpdateSeq sets the "seq" field to the value that was provided on create.
func (u *TelegramUserStateUpsertBulk) UpdateSeq() *TelegramUserStateUpsertBulk {
	return u.Update(func(s *TelegramUserStateUpsert) {
		s.UpdateSeq()
	})
}

// Exec executes the query.
func (u *TelegramUserStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TelegramUserStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramUserStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramUserStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
