// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/predicate"
	"github.com/go-faster/bot/internal/ent/telegramchannelstate"
	"github.com/go-faster/bot/internal/ent/telegramuserstate"
)

// TelegramUserStateQuery is the builder for querying TelegramUserState entities.
type TelegramUserStateQuery struct {
	config
	ctx               *QueryContext
	order             []telegramuserstate.OrderOption
	inters            []Interceptor
	predicates        []predicate.TelegramUserState
	withChannels      *TelegramChannelStateQuery
	withNamedChannels map[string]*TelegramChannelStateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TelegramUserStateQuery builder.
func (_q *TelegramUserStateQuery) Where(ps ...predicate.TelegramUserState) *TelegramUserStateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TelegramUserStateQuery) Limit(limit int) *TelegramUserStateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TelegramUserStateQuery) Offset(offset int) *TelegramUserStateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TelegramUserStateQuery) Unique(unique bool) *TelegramUserStateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TelegramUserStateQuery) Order(o ...telegramuserstate.OrderOption) *TelegramUserStateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChannels chains the current query on the "channels" edge.
func (_q *TelegramUserStateQuery) QueryChannels() *TelegramChannelStateQuery {
	query := (&TelegramChannelStateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramuserstate.Table, telegramuserstate.FieldID, selector),
			sqlgraph.To(telegramchannelstate.Table, telegramchannelstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, telegramuserstate.ChannelsTable, telegramuserstate.ChannelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TelegramUserState entity from the query.
// Returns a *NotFoundError when no TelegramUserState was found.
func (_q *TelegramUserStateQuery) First(ctx context.Context) (*TelegramUserState, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{telegramuserstate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TelegramUserStateQuery) FirstX(ctx context.Context) *TelegramUserState {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TelegramUserState ID from the query.
// Returns a *NotFoundError when no TelegramUserState ID was found.
func (_q *TelegramUserStateQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{telegramuserstate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TelegramUserStateQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TelegramUserState entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TelegramUserState entity is found.
// Returns a *NotFoundError when no TelegramUserState entities are found.
func (_q *TelegramUserStateQuery) Only(ctx context.Context) (*TelegramUserState, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{telegramuserstate.Label}
	default:
		return nil, &NotSingularError{telegramuserstate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TelegramUserStateQuery) OnlyX(ctx context.Context) *TelegramUserState {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TelegramUserState ID in the query.
// Returns a *NotSingularError when more than one TelegramUserState ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TelegramUserStateQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{telegramuserstate.Label}
	default:
		err = &NotSingularError{telegramuserstate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TelegramUserStateQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TelegramUserStates.
func (_q *TelegramUserStateQuery) All(ctx context.Context) ([]*TelegramUserState, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TelegramUserState, *TelegramUserStateQuery]()
	return withInterceptors[[]*TelegramUserState](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TelegramUserStateQuery) AllX(ctx context.Context) []*TelegramUserState {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TelegramUserState IDs.
func (_q *TelegramUserStateQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(telegramuserstate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TelegramUserStateQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TelegramUserStateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TelegramUserStateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TelegramUserStateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TelegramUserStateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TelegramUserStateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TelegramUserStateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TelegramUserStateQuery) Clone() *TelegramUserStateQuery {
	if _q == nil {
		return nil
	}
	return &TelegramUserStateQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]telegramuserstate.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.TelegramUserState{}, _q.predicates...),
		withChannels: _q.withChannels.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChannels tells the query-builder to eager-load the nodes that are connected to
// the "channels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TelegramUserStateQuery) WithChannels(opts ...func(*TelegramChannelStateQuery)) *TelegramUserStateQuery {
	query := (&TelegramChannelStateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannels = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Qts int `json:"qts,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TelegramUserState.Query().
//		GroupBy(telegramuserstate.FieldQts).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TelegramUserStateQuery) GroupBy(field string, fields ...string) *TelegramUserStateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TelegramUserStateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = telegramuserstate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Qts int `json:"qts,omitempty"`
//	}
//
//	client.TelegramUserState.Query().
//		Select(telegramuserstate.FieldQts).
//		Scan(ctx, &v)
func (_q *TelegramUserStateQuery) Select(fields ...string) *TelegramUserStateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TelegramUserStateSelect{TelegramUserStateQuery: _q}
	sbuild.label = telegramuserstate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TelegramUserStateSelect configured with the given aggregations.
func (_q *TelegramUserStateQuery) Aggregate(fns ...AggregateFunc) *TelegramUserStateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TelegramUserStateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !telegramuserstate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TelegramUserStateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TelegramUserState, error) {
	var (
		nodes       = []*TelegramUserState{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withChannels != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TelegramUserState).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TelegramUserState{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChannels; query != nil {
		if err := _q.loadChannels(ctx, query, nodes,
			func(n *TelegramUserState) { n.Edges.Channels = []*TelegramChannelState{} },
			func(n *TelegramUserState, e *TelegramChannelState) { n.Edges.Channels = append(n.Edges.Channels, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedChannels {
		if err := _q.loadChannels(ctx, query, nodes,
			func(n *TelegramUserState) { n.appendNamedChannels(name) },
			func(n *TelegramUserState, e *TelegramChannelState) { n.appendNamedChannels(name, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TelegramUserStateQuery) loadChannels(ctx context.Context, query *TelegramChannelStateQuery, nodes []*TelegramUserState, init func(*TelegramUserState), assign func(*TelegramUserState, *TelegramChannelState)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*TelegramUserState)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(telegramchannelstate.FieldUserID)
	}
	query.Where(predicate.TelegramChannelState(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(telegramuserstate.ChannelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TelegramUserStateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TelegramUserStateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(telegramuserstate.Table, telegramuserstate.Columns, sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramuserstate.FieldID)
		for i := range fields {
			if fields[i] != telegramuserstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TelegramUserStateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(telegramuserstate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = telegramuserstate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedChannels tells the query-builder to eager-load the nodes that are connected to the "channels"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *TelegramUserStateQuery) WithNamedChannels(name string, opts ...func(*TelegramChannelStateQuery)) *TelegramUserStateQuery {
	query := (&TelegramChannelStateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedChannels == nil {
		_q.withNamedChannels = make(map[string]*TelegramChannelStateQuery)
	}
	_q.withNamedChannels[name] = query
	return _q
}

// TelegramUserStateGroupBy is the group-by builder for TelegramUserState entities.
type TelegramUserStateGroupBy struct {
	selector
	build *TelegramUserStateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TelegramUserStateGroupBy) Aggregate(fns ...AggregateFunc) *TelegramUserStateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TelegramUserStateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramUserStateQuery, *TelegramUserStateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TelegramUserStateGroupBy) sqlScan(ctx context.Context, root *TelegramUserStateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TelegramUserStateSelect is the builder for selecting fields of TelegramUserState entities.
type TelegramUserStateSelect struct {
	*TelegramUserStateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TelegramUserStateSelect) Aggregate(fns ...AggregateFunc) *TelegramUserStateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TelegramUserStateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramUserStateQuery, *TelegramUserStateSelect](ctx, _s.TelegramUserStateQuery, _s, _s.inters, v)
}

func (_s *TelegramUserStateSelect) sqlScan(ctx context.Context, root *TelegramUserStateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
