// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/bot/internal/ent/predicate"
	"github.com/go-faster/bot/internal/ent/telegramchannelstate"
	"github.com/go-faster/bot/internal/ent/telegramuserstate"
)

// TelegramChannelStateUpdate is the builder for updating TelegramChannelState entities.
type TelegramChannelStateUpdate struct {
	config
	hooks    []Hook
	mutation *TelegramChannelStateMutation
}

// Where appends a list predicates to the TelegramChannelStateUpdate builder.
func (_u *TelegramChannelStateUpdate) Where(ps ...predicate.TelegramChannelState) *TelegramChannelStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *TelegramChannelStateUpdate) SetChannelID(v int64) *TelegramChannelStateUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *TelegramChannelStateUpdate) SetNillableChannelID(v *int64) *TelegramChannelStateUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *TelegramChannelStateUpdate) AddChannelID(v int64) *TelegramChannelStateUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TelegramChannelStateUpdate) SetUserID(v int64) *TelegramChannelStateUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TelegramChannelStateUpdate) SetNillableUserID(v *int64) *TelegramChannelStateUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPts sets the "pts" field.
func (_u *TelegramChannelStateUpdate) SetPts(v int) *TelegramChannelStateUpdate {
	_u.mutation.ResetPts()
	_u.mutation.SetPts(v)
	return _u
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (_u *TelegramChannelStateUpdate) SetNillablePts(v *int) *TelegramChannelStateUpdate {
	if v != nil {
		_u.SetPts(*v)
	}
	return _u
}

// AddPts adds value to the "pts" field.
func (_u *TelegramChannelStateUpdate) AddPts(v int) *TelegramChannelStateUpdate {
	_u.mutation.AddPts(v)
	return _u
}

// SetUser sets the "user" edge to the TelegramUserState entity.
func (_u *TelegramChannelStateUpdate) SetUser(v *TelegramUserState) *TelegramChannelStateUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TelegramChannelStateMutation object of the builder.
func (_u *TelegramChannelStateUpdate) Mutation() *TelegramChannelStateMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the TelegramUserState entity.
func (_u *TelegramChannelStateUpdate) ClearUser() *TelegramChannelStateUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TelegramChannelStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelegramChannelStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TelegramChannelStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelegramChannelStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TelegramChannelStateUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TelegramChannelState.user"`)
	}
	return nil
}

func (_u *TelegramChannelStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(telegramchannelstate.Table, telegramchannelstate.Columns, sqlgraph.NewFieldSpec(telegramchannelstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(telegramchannelstate.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(telegramchannelstate.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Pts(); ok {
		_spec.SetField(telegramchannelstate.FieldPts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPts(); ok {
		_spec.AddField(telegramchannelstate.FieldPts, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telegramchannelstate.UserTable,
			Columns: []string{telegramchannelstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telegramchannelstate.UserTable,
			Columns: []string{telegramchannelstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramchannelstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TelegramChannelStateUpdateOne is the builder for updating a single TelegramChannelState entity.
type TelegramChannelStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TelegramChannelStateMutation
}

// SetChannelID sets the "channel_id" field.
func (_u *TelegramChannelStateUpdateOne) SetChannelID(v int64) *TelegramChannelStateUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *TelegramChannelStateUpdateOne) SetNillableChannelID(v *int64) *TelegramChannelStateUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *TelegramChannelStateUpdateOne) AddChannelID(v int64) *TelegramChannelStateUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TelegramChannelStateUpdateOne) SetUserID(v int64) *TelegramChannelStateUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TelegramChannelStateUpdateOne) SetNillableUserID(v *int64) *TelegramChannelStateUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPts sets the "pts" field.
func (_u *TelegramChannelStateUpdateOne) SetPts(v int) *TelegramChannelStateUpdateOne {
	_u.mutation.ResetPts()
	_u.mutation.SetPts(v)
	return _u
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (_u *TelegramChannelStateUpdateOne) SetNillablePts(v *int) *TelegramChannelStateUpdateOne {
	if v != nil {
		_u.SetPts(*v)
	}
	return _u
}

// AddPts adds value to the "pts" field.
func (_u *TelegramChannelStateUpdateOne) AddPts(v int) *TelegramChannelStateUpdateOne {
	_u.mutation.AddPts(v)
	return _u
}

// SetUser sets the "user" edge to the TelegramUserState entity.
func (_u *TelegramChannelStateUpdateOne) SetUser(v *TelegramUserState) *TelegramChannelStateUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TelegramChannelStateMutation object of the builder.
func (_u *TelegramChannelStateUpdateOne) Mutation() *TelegramChannelStateMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the TelegramUserState entity.
func (_u *TelegramChannelStateUpdateOne) ClearUser() *TelegramChannelStateUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TelegramChannelStateUpdate builder.
func (_u *TelegramChannelStateUpdateOne) Where(ps ...predicate.TelegramChannelState) *TelegramChannelStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TelegramChannelStateUpdateOne) Select(field string, fields ...string) *TelegramChannelStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TelegramChannelState entity.
func (_u *TelegramChannelStateUpdateOne) Save(ctx context.Context) (*TelegramChannelState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelegramChannelStateUpdateOne) SaveX(ctx context.Context) *TelegramChannelState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TelegramChannelStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelegramChannelStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TelegramChannelStateUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TelegramChannelState.user"`)
	}
	return nil
}

func (_u *TelegramChannelStateUpdateOne) sqlSave(ctx context.Context) (_node *TelegramChannelState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(telegramchannelstate.Table, telegramchannelstate.Columns, sqlgraph.NewFieldSpec(telegramchannelstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TelegramChannelState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramchannelstate.FieldID)
		for _, f := range fields {
			if !telegramchannelstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != telegramchannelstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(telegramchannelstate.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(telegramchannelstate.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Pts(); ok {
		_spec.SetField(telegramchannelstate.FieldPts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPts(); ok {
		_spec.AddField(telegramchannelstate.FieldPts, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telegramchannelstate.UserTable,
			Columns: []string{telegramchannelstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telegramchannelstate.UserTable,
			Columns: []string{telegramchannelstate.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(telegramuserstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TelegramChannelState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telegramchannelstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
