-- Create "organizations" table
CREATE TABLE "organizations" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "html_url" character varying NULL, PRIMARY KEY ("id"));
-- Modify "repositories" table
ALTER TABLE "repositories" DROP COLUMN "owner", ALTER COLUMN "html_url" DROP NOT NULL, ADD COLUMN "organization_repositories" bigint NULL, ADD CONSTRAINT "repositories_organizations_repositories" FOREIGN KEY ("organization_repositories") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "repositories_full_name_key" to table: "repositories"
CREATE UNIQUE INDEX "repositories_full_name_key" ON "repositories" ("full_name");
