---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: gotd
  name: gotd:deploy
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "pods"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
