kind: Service
apiVersion: v1
metadata:
  namespace: gotd
  name: bot
spec:
  selector:
    app: bot

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot
  namespace: gotd
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: status
spec:
  rules:
    - host: bot.gotd.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot
                port:
                  number: 80
