{
 "title": "Go",
 "description": "Go dashboard for application",
 "tags": [
  "application",
  "go",
  "golang"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_goroutines, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(go_info{namespace=\"$namespace\", service=\"$service\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "timeseries",
   "description": "Average stack memory usage across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (go_memstats_stack_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: stack inuse (avg)"
    }
   ]
  },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}} (avg)"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod)(go_memstats_heap_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: heap reserved (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_heap_inuse_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: heap in use (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_heap_alloc_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: heap alloc (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_heap_idle_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: heap idle (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_heap_released_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: heap released (avg)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "timeseries",
   "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod)(go_memstats_mspan_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: mspan (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_mcache_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: mcache (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_buck_hash_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: buck hash (avg)"
    },
    {
     "expr": "avg by (pod)(go_memstats_gc_sys_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: gc (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}: obj mallocs/s (avg)"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "timeseries",
   "description": "Average allocation rate in bytes per second, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (pod)(rate(go_memstats_alloc_bytes_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}: bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod)(go_goroutines{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: goroutine count (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_mallocs_total{service=\"$service\", namespace=\"$namespace\"} - go_memstats_frees_total{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (go_memstats_next_gc_bytes{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}} next gc bytes (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod)(go_gc_duration_seconds{quantile=\"0\", service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: min gc time (avg)"
    },
    {
     "expr": "avg by (pod)(go_gc_duration_seconds{quantile=\"1\", service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}: max gc time (avg)"
    }
   ]
  }
 ]
}