name: atlas
on:
#  push:
#    branches:
#      - main
#  pull_request:
#    paths:
#      - 'migrations/*'
  workflow_dispatch:
jobs:
  lint:
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5430:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Mandatory unless "latest" is set below.
      - uses: ariga/atlas-action@v1
        with:
          dir: migrations
          dir-format: atlas
          dev-url: postgres://postgres:pass@localhost:5430/test?sslmode=disable