name: atlas
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'migrations/*'
  workflow_dispatch:
jobs:
  lint:
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5430:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth:
      - uses: ariga/atlas-action@v0
        with:
          dir: migrations
          dir-format: atlas
          dev-url: postgres://postgres:pass@localhost:5430/test?sslmode=disable