name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV
          echo "lintcache=$HOME/.cache/golangci-lint" >> $GITHUB_ENV

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
            ${{ env.lintcache }}
          key: lint-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            lint-${{ runner.os }}-go-

      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          args: --timeout 5m
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

  # Check if there are any dirty changes after go mod tidy
  check-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: true

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Check git diff
        run: git diff --exit-code
